newrelic/node-newrelic-superagent

package.json

* Updated `@newrelic/test-utilities` dependency to v3.0.0.

update test-utilities dep version

---

.github/PULL_REQUEST_TEMPLATE.md

Added GitHub PR template

---

README.md

* Updated the readme to follow New Relic standard template.
* Closes: https://github.com/newrelic/node-newrelic-superagent/issues/32

Updates readme to standard template with some content modifications.

---

.npmignore

* Added additional items to .npmignore.

Adds additional items to npm ignore.

---

CHANGELOG.md
CONTRIBUTING.md

* Updated to Apache 2.0 license.
* Bumped minimum peer dependency (and dev dependency) of newrelic (agent) to 6.11 for license matching.
* Added third party notices file and metadata for dependencies.
* Updated readme with more detail.
* Added issue templates for bugs and enhancements.
* Added code of conduct file.
* Added contributing guide.
* Added pull request template.
* Migrated CI to GitHub Actions.
* Added copyright headers to all source files.
* Added repository property to package.json.
* Removed Coveralls integration.
* Bumped minimum versions of tap, eslint and @newrelic/test-utilities.
* Added .vscode to .gitignore.
* Added additional items to .npmignore.
- https://github.com/newrelic/node-newrelic-superagent/pull/18
- …

Release v3.0.0

---

THIRD_PARTY_NOTICES.md
package.json
third_party_manifest.json

* Bumped node-test-utilities version to ^4.0.0.

Bumps node-test-utilities to ^4.0.0.

---

README.md

- Updated readme with community-plus header based on repolinter suggestion.
- Closes: #52

Updated readme with community-plus header

---

.github/workflows/ci-workflow.yml
package.json

* Added Node 14 to CI.
* Added `--no-coverage` flag to unit test runs.

Adds Node 14 to CI.

---

CODE_OF_CONDUCT.md

* Removed code of conduct file (fixes #56)

Removed code of conduct file

---

.github/workflows/ci-workflow.yml
package.json
tests/versioned/package.json

Remove Node v8.x from CI

---

CONTRIBUTING.md

* Fixed code of conduct links in contributing guide

Code of conduct

---

package.json

* Bumped `@newrelic/test-utilities` to ^5.1.0.

Bumps @newrelic/test-utilities ^5.1.0.

---

.github/workflows/ci-workflow.yml
package.json

Adds Node 16 to CI

---

CHANGELOG.md

* Added versioned tests to the files list within package.json
https://github.com/newrelic/node-newrelic-superagent/pull/67

release 5.0.1

---

.github/workflows/create-release.yml

* Added create-release workflow to automate creating git tag, publishing npm module and creating GitHub release

added create-release workflow

---

tests/versioned/package.json

* Pinned version of `superagent` to `<7.1.0` until author fixes bug.
Closes #78
A bug was shipped that wasn't caught by tests, see https://github.com/visionmedia/superagent/issues/1673.  Author plans to release new version.  They marked 7.1.0 as deprecated but never updated 7.0.2 as latest. We will have circle back and skip this version.

Pin version to <7.1.0

---

package-lock.json
package.json

* Resolved several dev-dependency audit warnings.
* Bumped `tap` to ^15.1.6."

Resolves several dev audit warnings.

---

THIRD_PARTY_NOTICES.md
package.json
third_party_manifest.json

* Removed versioned tests from npm artifact.
* partially fixes [#1027](https://github.com/newrelic/node-newrelic/issues/1027)

package.json: remove versioned tests

---

.github/ISSUE_TEMPLATE/story.md

add issue templates for jira linking NEWRELIC-3748

---

.c8rc.json
.github/workflows/ci-workflow.yml
README.md
THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

https://app.codecov.io/gh/newrelic/node-newrelic-superagent/tree/NR-60784-codecov
* Updated tests to use c8
* Added codecov upload to CI build
* Added badges 🙌🏻

NR-60784 wire up c8 and codecov for coverage collection

---

.github/workflows/ci-workflow.yml
package.json
third_party_manifest.json

* Updated CI to run against versions 16-20.
Closes #111

added node 20

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
tests/versioned/package.json
third_party_manifest.json

Dropped Node 14 from package.json and versioned tests. 
Closes #112 
Closes NR-142056

chore!: Dropped Node 14

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

Upgraded test utils, newrelic so that the agent can remove the unused shimmer.patchModule and shimmer.unpatchModule.

chore: updated @newrelic/test-utilities and newrelic to latest
